# Generated by Django 3.2 on 2026-06-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentunitenrollment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REVOKED', 'Revoked'), ('REAPPLIED', 'Reapplied')], default='PENDING', max_length=15),
        ),
    ]
