# Generated by Django 3.2 on 2026-07-15 07:29

from decimal import Decimal
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher/Lecturer'), ('STUDENT', 'Student'), ('WARDEN', 'Warden'), ('LIBRARIAN', 'Librarian'), ('ACCOUNTANT', 'Accountant')], default='STUDENT', max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='E.g., 2025/2026, 2026/2027', max_length=9)),
                ('term', models.CharField(choices=[('TERM_1', 'Term 1'), ('TERM_2', 'Term 2'), ('TERM_3', 'Term 3'), ('RECESS', 'Recess Term')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False, help_text='Designates if this is the active operational term')),
            ],
            options={
                'verbose_name': 'Academic Term',
                'verbose_name_plural': 'Academic Terms',
                'unique_together': {('academic_year', 'term')},
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The official title of the resource book', max_length=255, unique=True)),
                ('author', models.CharField(blank=True, help_text='Author(s) of the book', max_length=255, null=True)),
                ('isbn', models.CharField(blank=True, help_text='International Standard Book Number', max_length=50, null=True, unique=True)),
                ('total_copies', models.PositiveIntegerField(default=1, help_text='Total copies owned by the school')),
                ('available_copies', models.PositiveIntegerField(default=1, help_text='Currently available copies on shelves')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CourseUnit',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='attendance.course')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_or_number', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='attendance.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='attendance.course')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('reg_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='attendance.course')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='attendance.stream')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('courses', models.ManyToManyField(blank=True, related_name='teachers', to='attendance.Course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimetableBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('week_start_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_batches', to='attendance.academicterm')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='attendance.timetablebatch')),
                ('course_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.courseunit')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='attendance.stream')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.teacherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTermFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fees_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_fees', to='attendance.studentprofile')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='attendance.academicterm')),
            ],
            options={
                'verbose_name': 'Student Term Fee Balance',
                'verbose_name_plural': 'Student Term Fee Balances',
                'unique_together': {('student', 'term')},
            },
        ),
        migrations.CreateModel(
            name='StaffPaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money Transfer'), ('CASH', 'Cash Desk Payout')], default='BANK_TRANSFER', max_length=20)),
                ('reference_number', models.CharField(help_text='Salary slip bank reference or voucher transaction number ID', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='E.g., June Basic Salary, Overtime Allowance')),
                ('processed_by', models.ForeignKey(limit_choices_to={'role': 'ACCOUNTANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_staff_salaries', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(limit_choices_to={'role__in': ['ADMIN', 'TEACHER', 'WARDEN', 'LIBRARIAN', 'ACCOUNTANT']}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_payments', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(blank=True, help_text='The operational term under which this payout budget falls', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_payouts', to='attendance.academicterm')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(help_text='The deadline date for returning the resource')),
                ('return_date', models.DateField(blank=True, help_text='The exact day the book was returned', null=True)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued / Outstanding'), ('RETURNED', 'Returned & Verified')], default='ISSUED', max_length=20)),
                ('remarks', models.TextField(blank=True, help_text='Notes such as damage reports, late fees, etc.', null=True)),
                ('book', models.ForeignKey(help_text='The book being issued', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.book')),
                ('student', models.ForeignKey(blank=True, help_text='Student borrower (leave blank if borrowing is for a teacher)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='library_records', to='attendance.studentprofile')),
                ('teacher', models.ForeignKey(blank=True, help_text='Teacher borrower (leave blank if borrowing is for a student)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='library_records', to='attendance.teacherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FeePaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('BANK_DEPOSIT', 'Direct Bank Deposit'), ('MOBILE_MONEY', 'Mobile Money Transfer'), ('CASH', 'Cash Desk Payment')], default='BANK_DEPOSIT', max_length=20)),
                ('reference_number', models.CharField(help_text='Bank slip transaction number or mobile money TxID', max_length=100, unique=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('date_confirmed', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(limit_choices_to={'role': 'ACCOUNTANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('term_fee_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='attendance.studenttermfee')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Brief tagline of the complaint or incident summary', max_length=255)),
                ('details', models.TextField(help_text='Detailed narrative of what transpired')),
                ('severity', models.CharField(choices=[('MILD', 'Mild Case'), ('SEVERE', 'Severe Breach'), ('VERY_SEVERE', 'Very Severe / Critical')], default='MILD', max_length=15)),
                ('date_logged', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_logs', to='attendance.studentprofile')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.academicterm')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='attendance.department'),
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_marked', models.DateField(auto_now_add=True)),
                ('teacher_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('teacher_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('timetable_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.timetableentry')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], max_length=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RoomAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_at', models.DateTimeField(auto_now=True)),
                ('allocated_by', models.ForeignKey(limit_choices_to={'role': 'WARDEN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='attendance.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_allocations', to='attendance.studentprofile')),
                ('term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_allocations', to='attendance.academicterm')),
            ],
            options={
                'unique_together': {('student', 'term')},
            },
        ),
    ]
