# Generated by Django 3.2 on 2026-07-17 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='department',
            field=models.ForeignKey(blank=True, help_text='The academic department to which this book belongs (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='attendance.department'),
        ),
        migrations.AlterField(
            model_name='disciplinaryrecord',
            name='severity',
            field=models.CharField(choices=[('MILD', 'Mild Case'), ('SEVERE', 'Severe Breach'), ('VERY_SEVERE', 'Very Severe / Critical'), ('SUSPENDED_2W', 'Suspended (2 weeks)'), ('INDEF_SUSPENDED', 'Indefinitely Suspended'), ('EXPELLED', 'Expelled')], default='MILD', max_length=15),
        ),
    ]
