# Generated by Django 3.2 on 2026-06-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='attendance.Course'),
        ),
    ]
