# Generated by Django 3.2 on 2026-07-21 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20260717_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_reserve',
            field=models.BooleanField(default=False, help_text='Designates if this book is in the restricted Reserve Collection'),
        ),
        migrations.CreateModel(
            name='ReserveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Librarian Approval'), ('APPROVED', 'Approved for In-Library Access'), ('REJECTED', 'Application Declined'), ('COMPLETED', 'Fulfilled')], default='PENDING', max_length=20)),
                ('purpose_notes', models.TextField(blank=True, help_text='Reason for requesting this reserve title', null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_requests', to='attendance.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_requests', to='attendance.studentprofile')),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
    ]
