# Generated by Django 3.2 on 2026-07-10 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20260710_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher/Lecturer'), ('STUDENT', 'Student'), ('WARDEN', 'Warden'), ('LIBRARIAN', 'Librarian')], default='STUDENT', max_length=10),
        ),
        migrations.CreateModel(
            name='LibraryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255)),
                ('date_issued', models.DateField(default=django.utils.timezone.now)),
                ('is_returned', models.BooleanField(default=False)),
                ('date_returned', models.DateField(blank=True, null=True)),
                ('issued_by', models.ForeignKey(limit_choices_to={'role': 'LIBRARIAN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_books', to='attendance.studentprofile')),
            ],
        ),
    ]
