# Generated by Django 3.2 on 2026-07-21 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20260721_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserverequest',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserve_requests', to='attendance.teacherprofile'),
        ),
        migrations.AlterField(
            model_name='reserverequest',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserve_requests', to='attendance.studentprofile'),
        ),
    ]
