# Generated by Django 3.2 on 2026-07-10 08:43

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20260710_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher/Lecturer'), ('STUDENT', 'Student'), ('WARDEN', 'Warden'), ('LIBRARIAN', 'Librarian'), ('ACCOUNTANT', 'Accountant')], default='STUDENT', max_length=15),
        ),
        migrations.CreateModel(
            name='StudentFeeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fees_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_account', to='attendance.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FeePaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('BANK_DEPOSIT', 'Direct Bank Deposit'), ('MOBILE_MONEY', 'Mobile Money Transfer'), ('CASH', 'Cash Desk Payment')], default='BANK_DEPOSIT', max_length=20)),
                ('reference_number', models.CharField(help_text='Bank slip transaction number or mobile money TxID', max_length=100, unique=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('date_confirmed', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='attendance.studentfeeaccount')),
                ('processed_by', models.ForeignKey(limit_choices_to={'role': 'ACCOUNTANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
