# Generated by Django 3.2 on 2026-07-10 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20260710_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Brief tagline of the complaint or incident summary', max_length=255)),
                ('details', models.TextField(help_text='Detailed narrative of what transpired')),
                ('severity', models.CharField(choices=[('MILD', 'Mild Case'), ('SEVERE', 'Severe Breach'), ('VERY_SEVERE', 'Very Severe / Critical')], default='MILD', max_length=15)),
                ('date_logged', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_logs', to='attendance.studentprofile')),
            ],
        ),
    ]
