# Generated by Django 3.2 on 2026-07-10 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_disciplinaryrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money Transfer'), ('CASH', 'Cash Desk Payout')], default='BANK_TRANSFER', max_length=20)),
                ('reference_number', models.CharField(help_text='Salary slip bank reference or voucher transaction number ID', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='E.g., June Basic Salary, Overtime Allowance')),
                ('processed_by', models.ForeignKey(limit_choices_to={'role': 'ACCOUNTANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_staff_salaries', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(limit_choices_to={'role__in': ['ADMIN', 'TEACHER', 'WARDEN', 'LIBRARIAN', 'ACCOUNTANT']}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
