# Generated by Django 3.2 on 2026-07-10 12:33

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_staffpaymentrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='E.g., 2025/2026, 2026/2027', max_length=9)),
                ('term', models.CharField(choices=[('TERM_1', 'Term 1'), ('TERM_2', 'Term 2'), ('TERM_3', 'Term 3'), ('RECESS', 'Recess Term')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False, help_text='Designates if this is the active operational term')),
            ],
            options={
                'verbose_name': 'Academic Term',
                'verbose_name_plural': 'Academic Terms',
                'unique_together': {('academic_year', 'term')},
            },
        ),
        migrations.CreateModel(
            name='StudentTermFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fees_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_fees', to='attendance.studentprofile')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='attendance.academicterm')),
            ],
            options={
                'verbose_name': 'Student Term Fee Balance',
                'verbose_name_plural': 'Student Term Fee Balances',
                'unique_together': {('student', 'term')},
            },
        ),
        migrations.RemoveField(
            model_name='feepaymenttransaction',
            name='account',
        ),
        migrations.DeleteModel(
            name='StudentFeeAccount',
        ),
        migrations.AddField(
            model_name='disciplinaryrecord',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.academicterm'),
        ),
        migrations.AddField(
            model_name='feepaymenttransaction',
            name='term_fee_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='attendance.studenttermfee'),
        ),
        migrations.AddField(
            model_name='libraryrecord',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.academicterm'),
        ),
        migrations.AddField(
            model_name='roomallocation',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_allocations', to='attendance.academicterm'),
        ),
        migrations.AddField(
            model_name='staffpaymentrecord',
            name='term',
            field=models.ForeignKey(blank=True, help_text='The operational term under which this payout budget falls', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_payouts', to='attendance.academicterm'),
        ),
        migrations.AddField(
            model_name='timetablebatch',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_batches', to='attendance.academicterm'),
        ),
    ]
