# Generated by Django 3.2 on 2026-07-13 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20260710_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomallocation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_allocations', to='attendance.studentprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='roomallocation',
            unique_together={('student', 'term')},
        ),
    ]
